---
- name: "Wordpress installation using ansible on nginx + ubuntu"
  become: true
  hosts: all
  vars_files:
   - variables.yml
  tasks:

    - name: "installing packages"
      apt:
        name: "{{packages}}"
        state: present
        update_cache: true

    - name: "removing default conf file"
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default

    - name: "creating virtualhost"
      template:
        src: ./virtualhost.conf.tmpl
        dest: "/etc/nginx/sites-available/{{nginx_hostname}}"
        owner: "{{nginx_owner}}"
        group: "{{nginx_group}}"
      register: vhost_status

    - name: "Creating symlink"
      file:
        src: "/etc/nginx/sites-available/{{nginx_hostname}}"
        dest: "/etc/nginx/sites-enabled/{{nginx_hostname}}"
        state: link  

    - name: "creating document root for {{nginx_hostname}}"
      file:
        path: "{{doc_root}}"
        state: directory
        owner: "{{nginx_owner}}"
        group: "{{nginx_group}}"

    - name: "restarting nginx"
      when: vhost_status.changed == true
      service:
        name: nginx.service
        state: restarted

    - name: "starting/enabling mariadb-server" 
      service:
        name: mariadb
        state: started
        enabled: true

    - name: "setting root paswword for mariadb-server"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{mariadb_root_password}}"
        host_all: true

    - name: "removing anonymous users"
      mysql_user:
        login_user: "root"
        login_password: "{{mariadb_root_password}}"
        user: ""
        password: ""
        host_all: true
        state: absent

    - name: "creating database for wordpress"
      mysql_db:
        login_user: "root"
        login_password: "{{mariadb_root_password}}"
        name: "{{mariadb_extra_database}}"
        state: present

    - name: "creating user for wordpress"
      mysql_user:
        login_user: "root"
        login_password: "{{mariadb_root_password}}"
        user: "{{mariadb_extra_user}}"
        password: "{{mariadb_extra_password}}"
        host: "localhost"
        state: present
        priv: '{{mariadb_extra_database}}.*:ALL'

    - name: "downloading wp zip file"
      get_url:
        url: "{{wp_url}}"
        dest:  /tmp/wordpress.tar.gz

    - name: "extracting zip file"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true
      
    - name: "copying contents to {{doc_root}}"
      copy:
        src: /tmp/wordpress/
        dest: "{{doc_root}}"
        owner: "{{nginx_owner}}"
        group: "{{nginx_group}}" 
        remote_src: true

    - name: "creating {{doc_root}}/wp-config.php"
      template:
        src: ./wp-config.php.tmpl
        dest: "{{doc_root}}/wp-config.php"
        owner: "{{nginx_owner}}"
        group: "{{nginx_group}}"

    - name: "Post-installation restart"
      service:
        name: "{{item}}"
        state: restarted
        enabled: true
      with_items:
        - nginx
        - mariadb
